language: go
sudo: required
env:
  global:
    - BASE_DIR=/home/travis/gopath/src/github.com/palletone/go-palletone
    - ALL_LOG_PATH=/home/travis/gopath/src/github.com/palletone/go-palletone/bdd/node/log/all.log
    - GAS_TOKEN_ALL_LOG_PATH=/home/travis/gopath/src/github.com/palletone/go-palletone/bdd/GasToken/node/log/all.log
    - BDD_LOG_PATH=/home/travis/gopath/src/github.com/palletone/go-palletone/bdd/logs
    - CREATE_TRANS_DIR=createTrans
    - CONTRACT20_DIR=crt20Contract
    - SEQENCE721_DIR=crt721Seqence
    - UDID721_DIR=crt721UDID
    - VOTECONTRACT_DIR=voteContract
    - MULTIPLE_DIR=zMulti-node
    - DIGITAL_IDENTITY_DIR=DigitalIdentityCert
    - HD_WALLET_DIR=hdWallet
    - PACKET_DIR=packet
    - DEPOSIT_DIR=deposit
    - GAS_TOKEN_DIR=gasToken
    - MEDIATOR_VOTE_DIR=meidatorvote
    - APPLICATION_DIR=application
    - USER_CONTRACT_DIR=usercontract
    - BLACKLIST_DIR=blacklist
    - EXCHANGE_DIR=exchange
    - LOG_NAME=log.html
    - REPORT_NAME=report.html
    ##########  control testcase  ##############
    - IS_RUN_DEPOSIT=true
    - IS_RUN_TESTCONTRACTCASES=true
    - IS_RUN_CREATE_TRANS=true
    - IS_RUN_20CONTRACT=true
    - IS_RUN_721SEQENCE=true
    - IS_RUN_721UDID=true
    - IS_RUN_MULTIPLE=true
    - IS_RUN_DIGITAL=false
    - IS_RUN_VOTE=true
    - IS_RUN_GASTOKEN=true
    - IS_RUN_MEDIATOR_VOTE=true
    - IS_RUN_APPLICATION=true
    - IS_RUN_LIGHT=false
    - IS_RUN_BLACKLIST=true
    - IS_RUN_EXCHANGE=true
    - GO111MODULE=on
    - IS_UPLOAD=true
    - IS_RUN_HDWALLET=true
    - IS_RUN_PACKET=true
#    - 'SFTP_KEY=[base64-encoded-rsa-key]'
matrix:
  include:
    - os: linux
      dist: xenial
      go: 1.12.9
      env: multiple_nodes_bdd
      script:
        # - go build -mod=vendor ./cmd/gptn
        - make gptn
        #- cp bdd/light/testcases/!(preset.sh) bdd/node
        # - cp ./gptn bdd/node
        - cd bdd/node
        - chmod -R +x *
        - sudo -H chmod +w /etc/hosts
        - sudo -H sed -i 's/127.0.0.1 localhost/127.0.0.1/g' /etc/hosts
        - sudo -H sed -i '$a0.0.0.0 localhost' /etc/hosts
        - ./launchMultipleNodes.sh
        - netstat -ap | grep gptn
        - grep "mediator_interval" node1/ptn-genesis.json
        - grep "maintenance_skip_slots" node1/ptn-genesis.json
        - cd ${BASE_DIR}/bdd
        - mkdir -p ${BDD_LOG_PATH}
        #- if [ $IS_RUN_MULTIPLE == 'true' ]; then
        #  python -m robot.run -d ${BDD_LOG_PATH}/${MULTIPLE_DIR} -i normal ./testcase/zMulti-node;
        #  fi

        - if [ $IS_RUN_LIGHT == 'true' ]; then
          cd ./light;
          chmod +x ./bddstart.sh;
          ./bddstart.sh;
          fi

      after_script:
        - killall gptn
        - sleep 2
        - cd ${BASE_DIR}
        #- zip -j ./bdd/logs/zMulti-node.zip ./logs/zMulti-node/*
        - pwd
        - zip -j ./bdd/logs/light.zip ./logs/light/logs/*
        # - |
        #   if [ $IS_UPLOAD == 'true' ]; then
        #     # uplaod all log
        #     ./bdd/upload2Ftp.sh ${FTP_PWD} ${TRAVIS_BRANCH} ${TRAVIS_BUILD_NUMBER};
        - cd ${BASE_DIR}/bdd
        - ./targz_node.sh multiNode
        - |
          if [ $IS_UPLOAD == 'true' ]; then
            # uplaod all log
            ./upload2Ftp.sh ${FTP_PWD} ${TRAVIS_BRANCH} ${TRAVIS_BUILD_NUMBER};
            # echo ftp address
            echo "The path of all bdd log in vsftpd is 'ftp://182.92.193.121"
            echo "If you want to open it in explorer, you should close VPN first."
            echo "If you want to open in windows explorer, you should open Internet Explorer and open Settings->Adanced-Enable FTP Folder view"
          fi
      install:
        - sudo -H pip install --upgrade pip
        - sudo -H pip install robotframework==2.8.5
        - sudo -H pip install requests
        - sudo -H pip install robotframework-requests
        - sudo -H pip install demjson
        - sudo -H pip install pexpect
        - sudo -H apt-get install jq
        - sudo -H apt-get install tcl tk expect
        - sudo -H apt-get install lftp
        - chmod +x bdd/upload2Ftp.sh bdd/targz_node.sh


addons:
  apt:
    update: true

notifications:
  email:
    recipients:
      - travisreport@163.com
    on_success: always # default: change
    on_failure: always
