name: BDDS
on: [push]
jobs:

  fabricbdd:
    name: UserContract-fabricbdd
    runs-on: ubuntu-latest
    steps:

    - name: Prepare fabric
      run: |
          cd $HOME
          mkdir gopath
          cd gopath
          export GOPATH=$pwd
          mkdir -p src/github.com/hyperledger
          cd src/github.com/hyperledger
          git clone -b v1.4.0 https://github.com/hyperledger/fabric-samples
          cd ./fabric-samples/scripts
          ./bootstrap.sh -b
          docker images
          cd $GOPATH/src/github.com/hyperledger
          wget https://github.com/hyperledger/fabric/releases/download/v1.4.0/hyperledger-fabric-linux-amd64-1.4.0.tar.gz
          tar zxvf hyperledger-fabric-linux-amd64-1.4.0.tar.gz
          export PATH=$PATH:/home/pallet/work/src/github.com/hyperledger/bin
          peer version


