name: MultipleNodesBDD
on: push
jobs:
  job1:
    name: Multiple Nodes BDD
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
 
    - name: Install Dependencies
      run: |
          sudo -H pip install --upgrade pip
          sudo -H pip install robotframework==2.8.5
          sudo -H pip install requests
          sudo -H pip install robotframework-requests
          sudo -H pip install demjson
          sudo -H pip install pexpect
          sudo -H apt-get install expect
          sudo -H apt-get install lftp

    - name: Build Gptn
      run: |
          go build -mod=vendor ./cmd/gptn

    - name: Run Gptns
      run: |
          cd bdd/node
          chmod -R +x *
          sudo -H chmod +w /etc/hosts
          sudo -H sed -i 's/127.0.0.1 localhost/127.0.0.1/g' /etc/hosts
          sudo -H sed -i '$a0.0.0.0 localhost' /etc/hosts
          ./launchMultipleNodes.sh
          netstat -ap | grep gptn
          grep "mediator_interval" node1/ptn-genesis.json
          grep "maintenance_skip_slots" node1/ptn-genesis.json

    - name: Run Multiple Nodes BDD
      run: |
          python -m robot.run -d ./bdd/logs/zMulti-node -i normal ./bdd/testcase/zMulti-node

    - name: Run light bdd
      run: |
        cd bdd/light
        chmod +x ./bddstart.sh
        ./bddstart.sh
        
    - name: Upload to Ftp
      if: always()
      run: |
          killall -9 gptn
          zip -j bdd/logs/zMulti-node_log.zip bdd/logs/zMulti-node/*
          zip -j bdd/logs/light.zip bdd/logs/light/*
          cd bdd
          chmod +x ./upload2Ftp.sh ./targz_node.sh
          ./targz_node.sh multiNode
          ./upload2Ftp.sh ${{secrets.FTP_PWD}} "Actions-"${GITHUB_REF##*/} ${GITHUB_SHA} $PWD/logs

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: multipleLogs
        path: bdd/logs
