name: UT&Lint
on: [push]
jobs:
  job1:
    name: UT
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -mod=vendor ./cmd/gptn

      - name: Test
        run: go test -mod=vendor ./...

  job2:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Export GOPATH
        run: echo "::set-env name=GOPATH::$(go env GOPATH)"
      - name: Append GOPATH onto PATH
        run: echo "::set-env name=PATH::$PATH:$GOPATH/bin"
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.21.0
      - run: golangci-lint --version
      - run: golangci-lint run ./...